# Generated by Django 3.2.12 on 2025-01-05 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_actividad_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajero',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='viajero', to='auth.user'),
            preserve_default=False,
        ),
    ]
