# Generated by Django 3.2.12 on 2025-01-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_viajero_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viajero',
            name='user',
        ),
    ]
