# Generated by Django 3.2.12 on 2025-01-05 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_viajero_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajero',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajero', to=settings.AUTH_USER_MODEL),
        ),
    ]
