# Generated by Django 5.1.4 on 2025-01-06 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_viajero_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerariocompartido',
            name='itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerario_compartido', to='core.itinerario'),
        ),
        migrations.AlterField(
            model_name='viajero',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='viajero', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
