# Generated by Django 5.1.4 on 2024-12-30 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='itinerario',
        ),
        migrations.DeleteModel(
            name='Destino',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='viajero',
        ),
        migrations.RemoveField(
            model_name='itinerariocompartido',
            name='itinerario',
        ),
        migrations.DeleteModel(
            name='Viajero',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Itinerario',
        ),
        migrations.DeleteModel(
            name='ItinerarioCompartido',
        ),
    ]
